apiVersion: v1
kind: Pod
metadata:
  namespace: cau2
  name: busybox
  labels:
    access: accepted
spec:
  containers:
  - name: tools
    image: busybox
    resources: {}
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'busybox running'; sleep 10;done"]