apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx:1.18.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 128M
            cpu: 100m
          limits:
            memory: 128M
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30000